### ISSUE TITLE
Discord on fire "fix"

### ISSUE THREAD

**Issue by kazasho** [avaire/avaire#13]
[version]: https://github.com/avaire/avaire/blob/master/build.gradle#L10
[guild]: https://discord.gg/gt2FWER
[stack overflow]: https://stackoverflow.com/questions/tagged/java

## General Troubleshooting

Hey there! Before you report a bug or suggest a new feature,
  please make sure to follow these steps first!
  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest Ava version][version].
- [x] I have checked the branches or the maintainers' PRs for upcoming features/bug fixes.

> This is not the place to learn Java. Please refer to [StackOverflow][stack overflow]
  for your general programming questions.

### Issue Type

- [ ] Bug Report
- [x] Feature Request

> For questions join the official AvaIre discord server: https://discord.gg/gt2FWER

### Description

Discord keeps going on fire.

When the bot queries the discord API and does not get a response, or get's disconnected, push it into a reconnect loop with different timers.

Like, reconnect every 5/10/15 minutes. (Without the bot stopping on trying to reconnect)

If there is any way that this state can be tracked that is.

**Comment by Senither** [comment]
The thing about this is that Ava actually already does this, however due to some issues on Discords side (which seems to be region specific), the bot doesn't always come back online for all the servers the bot is on, there have even been instances of two servers seeing the bot as online and offline at the same time, even if they share the same shard.

I got plans for making a website at some point that will always display the current state of each shard within Ava, until that is made you can use the internal API tho.
http://api.avairebot.com/stats
I'd recommend using something like [JSON Formatter](https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa?hl=en) if you're using Chrome, or somthing similar if you're using another browser, since it makes looking over the output a lot easier.
