### ISSUE TITLE
Add a channel medialock command

### ISSUE THREAD

**Issue by a2937** [avaire/avaire#67]
## General Troubleshooting

Hey there! Before you report a bug or suggest a new feature,
  please make sure to follow these steps first!
  
- [X] I have checked for similar issues.
- [X] I have updated to the [latest Ava version][version].
- [X] I have checked the branches or the maintainers' PRs for upcoming features/bug fixes.

> This is not the place to learn Java. Please refer to [StackOverflow][stack overflow]
  for your general programming questions.

### Issue Type

- [ ] Bug Report
- [X] Feature Request

> For questions join the official AvaIre discord server: https://discord.gg/gt2FWER

### Description

I would like a command called <code>"!medialock"</code> added to AvaIre. The way the command works is that it would toggle a boolean called mediaLocked with the channel the command was issued in. By default the boolean is false. The bot would send a message saying this channel has been added to the list of media only channels, or if the channel has been removed from the list a message would be saying the channel has been removed from the list.  The ideal place for this boolean would be in the ChannelTransformer.java file, but I am not sure what table I need to create a migration for. Next it would scan for messages that do not start with the prefix char and also have the channel's media lock variable set to true. This if statement would be inserted into the MessageEventAdapter.java in the onMessageReceived method. The next thing I would do is check to see if the message has any attachments. If so I would iterate through each one and store the file extension into a variable, as it can easily be done with a substring starting from the last index of a period plus 1. Next I would check to see if the attachment is an image by using the Message.Attachment.isImage method and also check the extension against known media file extensions added to a list. If either condition is true, the message gets deleted. If there are no attachments, I would check to see if the message is a valid url; the way I would handle it is using the Apache Commons Validator  UrlValidator. After retrieving an instance it all that needs done is to use the isValid method. If it is not a valid URL, the message gets deleted. I would also add an empty block as a precaution that check to see if it is a valid URL as a precaution against it being deleted from an else statement that deletes any other message types.

**Comment by Senither** [comment]
What? If you're suggesting a feature for the bot, it would be a lot easier if you describe what the feature should do, and how you want it to work(as a user in Discord), instead of saying how you would go about implementing it in code.

Simply describing the feature would be a lot better, so other people can easily understand what you want to be added, and so they can go figure out their own implementation for the feature, instead of having to decipher your implementation "instructions" and trying to figure out what the feature should do from that.

I'll just close the issue for now, if you want you can create a new issue for the suggestion that is a bit more descriptive so people can understand your suggestion a bit easier.
